### ISSUE TITLE
定制版添加插件请求

### ISSUE THREAD

**Issue by dhlsam1987** [ardanzhu/Opwrt_Actions#2]
大佬，非常好的固件，可以加上l大最新的airplay2和PCHiFi 数字转盘遥控还有新的cifs-mount这个插件么，这样r2s插了usb声卡就可以当播放器了，cifs-mount这个就不用老的smb 就可以挂载nas上的盘做下载盘了
CONFIG_PACKAGE_luci-app-cifs-mount=y
CONFIG_PACKAGE_luci-app-music-remote-center=y
CONFIG_PACKAGE_luci-app-airplay2=y
airplay2需要的kernel 
CONFIG_PACKAGE_kmod-sound-core=y
CONFIG_PACKAGE_kmod-usb-audio=y

**Comment by ardanzhu** [comment]
可以自行Fork过去，在r2s_opt.config里加上你所需要的，即可自动编译了

**Comment by dhlsam1987** [comment]
好嘞
